WebAssembly/WASI

docs/HighLevelGoals.md

This PR adds a High-Level Goals document, in the spirit of the [core WebAssembly High-Level Goals](https://github.com/WebAssembly/design/blob/master/HighLevelGoals.md).
Of particular note, this document lays out a rough outline for an MVP milestone, which roughly contains the feature set of what's currently called [WASI Core](https://github.com/WebAssembly/WASI/blob/master/design/WASI-core.md), though that's just a starting point. That said, the Subgroup can also continue to work on features outside the MVP scope concurrently.
Comments, questions, and suggestions welcome!

Add a HighLevelGoals.md document.

---

design/application-abi.md

This is that start of a document regarding what we expect from a valid was WASI application.    Not ready to land yet. 
Does this kind of thing belong here?  If not then where?
Perhaps I should include here documentation of the current status quo (i.e. _start function etc) along with the forward looking plans?
See https://github.com/WebAssembly/WASI/issues/24 and https://github.com/WebAssembly/WASI/issues/19

Add application-abi describing the current unstable WASI application ABI

---

meetings/README.md

Note that there's no meeting next week as several of us will be at the
CG meeting that day.

Add a note that there's no meeting on 06-13.

---

.github/workflows/main.yml
tools/witx/tests/wasi_unstable.rs

This adds some basic GitHub Actions configuration to build/test the `witx` crate, which also validates the `phases/unstable/witx/wasi_unstable_preview0.witx` file in this repo. I figured it'd be good to start out with some testing and if we need binary releases can layer that on afterwards.

Add GitHub Actions CI for `witx` crate

---

phases/ephemeral/witx/wasi_ephemeral_preview0.witx
tools/witx/tests/wasi_unstable.rs

`wasi_ephemeral_preview0` is meant to be versioned, so that it can be
superceded by new versions in the future.
Also, update the witx testsuite to test all the current witx files.

Fix the name of `wasi_ephemeral_preview0` and update tests.

---

tools/witx/src/ast.rs
tools/witx/src/io.rs
tools/witx/src/lib.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/sexpr.rs
tools/witx/src/toplevel.rs
tools/witx/src/validate.rs
tools/witx/tests/wasi_unstable.rs

* Friendly public API to `Document` and `Module` - expose a getter and an iterator for each kind of definition in each, rather than expose the internal Vec<Definition>/HashMap<Id, Entry> datastructures.
* Implement `PartialEq` and `Eq` for all AST nodes. The Document and Module implementations are implemented manually, and are not sensitive to the order of definitions.
* Make a standalone `parse(&str) -> Result<Document,...>` function available. This uses `MockFs` under the hood.
* Factor out IO to a separate module in the crate. Add variants of error reporting that looks up the location of the error using `WitxIo`
* Add a `Render` trait that converts AST nodes back into s-expressions. A separate SExpr enum is used because it needs to own `String`s, rather than have refs (`&'a str`) and …

witx crate: improve public API

---

phases/ephemeral/witx/wasi_ephemeral_preview0.witx
phases/old/witx/wasi_unstable.witx
phases/unstable/witx/wasi_unstable_preview0.witx

This PR makes changes to `wasi_unstable_preview0.witx` to align with the current implementations (wasi-libc, wasi-common, and the wasi rust crate)
* `environ_sizes_get` returns an `errno_t` as its first result
* `path_open` takes a `fdflags_t` argument.
* `proc_sched_yield` is actually called `sched_yield`
Open question: These changes are seeking to make the witx document descriptive, rather than prescriptive. `wasi_unstable_preview0.witx` is also out of sync with current implementations by using the `wasi_unstable_preview0` module name, where current implementations use `wasi_unstable`.
Should we instead make `phases/old/witx/wasi_unstable.witx` that describes current (pre-`preview0`) implementations? Or should `preview0`?

wasi_unstable_preview0.witx: fixes to match current implementations

---

tools/witx/src/parser.rs
tools/witx/src/render.rs

"data" isn't currently used by any witx files; we're using `pointer`
and `const_pointer` with explicit lengths instead, as these handle
mutable buffers in a much simpler way.

Remove the "data" builtin type.

---

tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/lib.rs
tools/witx/src/moduletype.rs
tools/witx/src/validate.rs

Also ports in a fix that should have been in #96 .
This PR defines a mapping of interface function types to module types. This mapping reflects the way witx maps to the existing implementations of WASI:
* Array, Data, and String types are passed as a pointer and a length
* Structs and Union types are passed as a pointer
* Pointer and ConstPointer are passed as I32. This is considered passing by value.
* All other types can be passed by value - integer and floats get mapped to the smallest atom that can represent them.
* the first result type is returned by value. validation requires that a pass-by-value datatype is used here.
* subsequent result types are passed as arguments, by reference.

witx crate: calculate module type signature of an interface function

---

tools/witx/Cargo.toml
tools/witx/src/coretypes.rs

The merge of #102 followed by #101 left in a use of BuiltinType::Data that breaks witx.
Fix that, and bump the version to 0.3.0 for publishing on crates.io

fix & release witx 0.3.0

---

meetings/2019/WASI-10-15.md

Attendees of this meeting should be members of the WebAssembly CG;
see the included link for details.
And, the host for this in-person meeting has requested we provide a
list of attendees, so please email Dan Gohman if you plan on
attending.

Update the logistics for the 10-15 in-person meeting.

---

phases/ephemeral/witx/wasi_ephemeral_preview.witx
tools/witx/tests/wasi_unstable.rs

The ephemeral module isn't meant to be versioned, so remove the "0"
version number.

Remove the "0" from the ephemeral module name.

---

phases/ephemeral/docs/wasi_ephemeral_preview.md
phases/ephemeral/witx/typenames.witx
phases/old/docs/wasi_unstable_preview0.md
phases/old/witx/typenames.witx
phases/unstable/docs/wasi_unstable_preview0.md
phases/unstable/witx/typenames.witx

Move `CLOCK_REALTIME` to be the first `clockid_t` value. This change
reflects the definitions used in [existing practice], so this patch
updates the `wasi_unstable_preview0` and `wasi_unstable` definitions
as well.
This is the same change as #41, but updated for the WASI repository's
new phases directory structure.
[existing practice]: https://github.com/CraneStation/wasi-libc/blob/master/libc-bottom-half/headers/public/wasi/core.h#L42

Reorder the `clockid_t` values to match existing practice.

---

.github/workflows/main.yml

Use `bash` as the default shell for installing Rust as `&&` is not a valid
command separator in PowerShell.

Fix CI on Windows.

---

phases/ephemeral/docs/wasi_ephemeral_preview.md

This commit updates the documentation for `__wasi_args_get` and
`__wasi_environ_get` to make it explicit that it is the caller's responsibility
to allocate a terminating NULL pointer, if necessary.
Fixes #27.

Make `__wasi_args_get` and `__wasi_environ_get` docs more explicit.

---

phases/ephemeral/witx/typenames.witx

As noticed in
https://github.com/rust-lang/rust/pull/65617#issue-330088745,
the `clock.identifier` field in `subscription_t` isn't used for
anything. It came from CloudABI, where it appears to be a holdover from
an earlier API feature which is no longer present.

Remove `subscription_t`'s `clock.identifier` field.

---

phases/ephemeral/docs/wasi_ephemeral_preview.md
phases/ephemeral/witx/typenames.witx

This commit changes the type for `__wasi_linkcount_t` to 64-bits to support
large link counts.
Fixes #70.

Change hard link count to 64-bits.

---

phases/ephemeral/witx/typenames.witx
phases/old/witx/typenames.witx
phases/unstable/witx/typenames.witx

Add the `flags` field to `subscription_clock_t`, which was accidentally
omitted. This change reflects the definitions used in [existing practice],
so this patch updates the `wasi_unstable_preview0` and `wasi_unstable`
definitions as well.
[existing practice]: https://github.com/CraneStation/wasi-libc/blob/master/libc-bottom-half/headers/public/wasi/core.h#L421

Fix the missing `flags` field in `subscription_clock_t`.

---

phases/ephemeral/witx/typenames.witx
phases/old/witx/typenames.witx
phases/unstable/witx/typenames.witx

This matches existing practice, so update the `unstable` and `old`
definitions too.

Make `eventtype_t` an enum rather than a flags.

---

phases/ephemeral/witx/typenames.witx
phases/old/witx/typenames.witx
phases/unstable/witx/typenames.witx
tools/witx/src/parser.rs
tools/witx/src/render.rs

Instead of defining `flags` with `(flag $FOO)`, just use `$FOO`,
which is more consistent with `enum`.

Change the `flags` syntax to be more consistent with `enum`.

---

phases/ephemeral/witx/wasi_ephemeral_preview.witx
phases/old/witx/wasi_unstable.witx
phases/unstable/witx/wasi_unstable_preview0.witx

This fixes the old versions too, as this change reflects current
practice.

Correct the return type of `fd_filestat_get`.

---

tools/witx/src/validate.rs

Currently, validation errors (which use `Location` to render error messages) display the wrong line and column because wast's Span::linecol_in uses 0-indexed lines and columns, but Location uses 1-indexed lines and columns. Trivial fix.

witx: convert from 0-indexed line and col to 1-indexed

---

phases/ephemeral/witx/wasi_ephemeral_preview.witx
phases/old/witx/wasi_unstable.witx
phases/unstable/witx/wasi_unstable_preview0.witx

This fixes the `*.witx` for the old definition of `path_symlink` to
ensure that the `old_path` argument comes first.

Fix old definition of `path_symlink`

---

.gitignore
tools/witx/Cargo.toml

Add a basic .gitignore for working with Rust code, and add cargo features for witx's Cargo.toml.

Add a .gitignore and add Cargo.toml features

---

phases/ephemeral/witx/typenames.witx
phases/ephemeral/witx/wasi_ephemeral_preview.witx
phases/old/snapshot_0/witx/typenames.witx
phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/witx/typenames.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx
tools/witx/tests/wasi.rs

Witx files started out encoding the types directly from the wasi/core.h header, including the C rules around identifier capitalization and namespacing.
This PR drops those conventions that are specific to the C language. We do so uniformly in each witx file, meaning we change both the current unstable and the contents of `phases/old`, so that code generators that know about these new conventions can still support all witx files in this repo.
I performed the following changes, mechanically when possible (leaving the sed script in the commit message):
* Drop trailing `_t` from all typenames.
* Change all $SHOUTY_SNAKE_CASE identifiers to $snake_case.
* Remove repeated prefixes from flag and enum variants: e.g. drop right_ prefix on all $rights
* Most cases of the above was removing the …

Mechanical witx naming convention changes

---

phases/ephemeral/witx/typenames.witx
tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/docs.rs
tools/witx/src/lib.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/validate.rs

`handle` is a kind of datatype for foreign references, or capabilities: it is opaque (has no in-memory representation), and is passed as a u32 index.
In ephemeral, `fd_t` is changed to be a handle, rather than a u32.

witx: add handles kind

---

tools/witx/Cargo.toml

witx depends on wast 3.0.1, but it uses the comment() method of the
Cursor type, which doesn't exist in version 3.0.1. This results in a
build failure if attempting to build witx against wast 3.0.1. That
method exists in the current 3.0.4, so update the wast dependency to
3.0.4.

witx: Depend on wast 3.0.4 to fix build failure with 3.0.1

---

tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/docs.rs
tools/witx/src/lib.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/toplevel.rs
tools/witx/src/validate.rs
tools/witx/tests/multimodule.rs
tools/witx/tests/wasi.rs

The `witx::ast` types had some confusing choices that I blame on building the first draft of the tool in a hurry. This redesigns the AST a bit:
* I used `Datatype`/`datatype` in a number of places where witx syntax and wasm just call things `type`s. The data-prefix has been dropped in many places. `StructDatatype`, `UnionDatatype` and friends still retain the "data" part of the name, but that seems less problematic.
* instead of two enumerations (`DatatypeIdent` and `DatatypeVariant`) holding different variations (arrays and pointers and builtins falling under Ident, everything else in variant) there is now just one enum `Type` that has each possible variation in a datatype
* `Type`s can either be anonymous (e.g. an `(array u8)` in a function argument) or named (by `(typename ...)`. An …

Re-organize witx AST

---

tools/witx/Cargo.toml
tools/witx/src/lib.rs
tools/witx/src/validate.rs

Straightforward upgrade of the error deriving crate. I'll publish this as 0.6.0 once merged.

Switch `witx` crate from using `failure` to `thiserror`, bump to 0.6.0

---

tools/witx/src/layout.rs
tools/witx/src/lib.rs
tools/witx/src/render.rs

Based on #164 
This is useful for validating pointers, enums, and flags in host code.

Compute layout of datatypes according to C ABI

---

phases/ephemeral/witx/wasi_ephemeral_args.witx
phases/ephemeral/witx/wasi_ephemeral_environ.witx
phases/ephemeral/witx/wasi_ephemeral_fd.witx
phases/ephemeral/witx/wasi_ephemeral_path.witx
phases/ephemeral/witx/wasi_ephemeral_random.witx
tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/docs.rs
tools/witx/src/layout.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs

This will allow the generated C header file to use [char8_t].
[char8_t]: https://en.cppreference.com/w/cpp/keyword/char8_t
Fixes #6.

Add a char8 type to represent data which is expected to be valid UTF-8.

---

phases/ephemeral/witx/wasi_ephemeral_proc.witx
tools/witx/src/ast.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/validate.rs

This will allow us to automatically add `_Noreturn` to `proc_exit` in C,
and `-> !` in Rust, rather than special-casing it.

Add a noreturn keyword to annotate functions expected to not return.

---

phases/ephemeral/witx/typenames.witx
tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/docs.rs
tools/witx/src/layout.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/validate.rs

This will allow code generators to know which types are sensitive to
wasm32 vs wasm64 without special-casing the `size` type.

Add a `usize` type to indicate types which will change size on wasm64.

---

phases/ephemeral/witx/typenames.witx
phases/ephemeral/witx/wasi_ephemeral_fd.witx
phases/ephemeral/witx/wasi_ephemeral_path.witx

Add functions and types to query and set the filesystem permissions of
a file: read, write, execute (for files), and search (for directories).
These permissions aren't the only thing which determines whether a given
file or directory can be accessed; hosts may impose additional arbitrary
security restrictions not reflected here.
WASI itself does not currently have the ability to execute files, so the
meaning of "execute" here is entirely up to the host filesystem.
These are similar to fchmod/fchmodat/fstat/fstatat in POSIX, though
there are some differences:
- This doesn't surface POSIX's setuid, setgid, or sticky bits. These can
be added in the future if needed, though they'll require additional
security and portability considerations.
- This uses separate flags for "execute" on files vs …

Add functions for working with file permissions.

---

tools/witx/src/validate.rs
tools/witx/tests/anonymous.rs

If you need to use a witx struct, union, enum, flags, or handle, you should please give it a name. This is an artificial restriction to make it easier to write backends for witx.
This doesn't actually happen in our current witx specs of wasi, but its accepted by the validator as part of #154.
Adds a set of tests of which sorts of types can and can't be used anonymously.

witx: exclude structs, unions, enums, flags, and handles from being declared anonymously

---

tools/witx/src/ast.rs
tools/witx/src/coretypes.rs
tools/witx/src/docs.rs
tools/witx/src/layout.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/validate.rs

Minor change to move `USize` from being a variant of `Type` to a variant of `BuiltinType`. The syntax `(@witx usize)` is different from the ordinary BuiltinType syntax `u32`, but otherwise its the same sort of thing as a BuiltinType. The `String` BuiltinTypes also will have a different representation for wasm64 targets.
This is more of a code review on #175, but unfortunately I missed that PR when it went up.

witx: make USize a BuiltinType

---

phases/snapshot/docs/wasi_unstable_preview1.md

I'm sure this isn't the only place the markdown has diverged from the spec, but it was simple enough to correct.
Closes #188

wasi_unstable_preview1.md: fix deleted field, reported in #188

---

phases/ephemeral/witx/typenames.witx

Every other filetype defined by POSIX for stat is in here,
so add FIFO to round things out.

Add FIFO filetype to match POSIX

---

tools/witx/src/validate.rs

ints are like enums or flags - they only really make sense to have a name.
Lets merge this before #201

witx validator: reject anonymous int type declarations

---

phases/snapshot/witx/typenames.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx

This commit fixes some links in different places in the docs
sections in `snapshot1` `*.witx` files so that they are consistent
with type naming throughout the document. This will aid correct
Markdown link generation by the `witx` tool directly from `*.witx`
files.
Note that thanks to this fix, the links are now correctly generated by `witx`
tool with the new docs generator introduced in #194.

Fix some links in the docs

---

tools/witx/Cargo.toml
tools/witx/src/main.rs

IMHO, `structopt` generally makes things somewhat cleaner and is worth
moving `witx` to `structopt` from `clap` for added readability and
extendability of the tool in the future.

Replace clap with structopt

---

phases/ephemeral/witx/wasi_ephemeral_poll.witx

`poll` with no subscriptions is effectively an infinite hang. Since wasm
has no signals, use cases which involve waking up a libc `pause` call, which
is implemented in terms of a poll with no subscriptions, aren't applicable.
So all `pause` can do is suspend the program until the host environment
terminates it.
One situation where that's useful is in debugging, as it's sometimes useful
to be able to suspend a process in place so that it can be inspected by a
debugger. However, that doesn't require a fully infinite suspend; a suspend
with a long timeout is adequate.
Making the no-subscriptions case an error can help catch cases where
applications unintentionally enter infinite loops.

Make poll return errno::inval if there are no subscriptions.

---

phases/ephemeral/docs.md

#193 was based on master before #204, but merged afterwards, so CI didn't catch this

Fix CI on `master`: regen ephemeral docs

---

phases/ephemeral/witx/typenames.witx

Ken Thompson was once asked what he would do differently if he were
redesigning the UNIX system. His reply: "I'd spell creat with an e."
- https://en.wikiquote.org/wiki/Ken_Thompson#Quotes

Rename `creat` to `create`.

---

phases/ephemeral/witx/typenames.witx

This makes it more consistent with naming through the rest of the witx
specs.

Rename $subscription_fd_readwrite's $fd member to $fd.

---

phases/ephemeral/witx/wasi_ephemeral_random.witx

The buffer contains arbitrary bytes, not UTF-8-encoded bytes, so use
`u8` rather than `char8`.
Fixes #184.

Change `random`'s buffer back to `u8`.

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

The word "type" in the descriptions of `$prestat_u::dir` and `$prestat_dir` should be clarified as `$pr_type`.
We can actually easily infer from the context, but I felt confused a little at first.
Fix: https://github.com/WebAssembly/WASI/issues/221

Clarify "type" is $pr_type in $prestat_u::dir and $prestat_dir

---

phases/ephemeral/docs.md
phases/ephemeral/witx/wasi_ephemeral_fd.witx

It appears that the `permissions` argument to `permissions_set()` was labeled as an output instead of an input.

update fd_permissions_set() signature

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

This commit fixes a `dircookie` comment string of its only const
member `start`. Effectively, due to the fact that one semicolon
was missing, the docs were not properly generated.

Fix const description in ephemeral

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

This pull request is part of issue #209.

Rename acces to access #209

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

Remove $process_cputime_id and $thread_cputime_id.
Some implementations will not have one wasm nanoprocess per OS process,
or one wasm thread per OS thread, making it difficult to implement
$process_cputime_id meaningfully. Also, the concept of "cputime"
available in most host environments isn't easy to directly connect to
what we might expect "cputime" to mean for wasm code.
These correspond to `CLOCK_PROCESS_CPUTIME_ID` and `CLOCK_THREAD_CPUTIME_ID`
in POSIX, which are optional:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html

Remove the cputime clocks.

---

phases/ephemeral/docs.md
phases/ephemeral/witx/wasi_ephemeral_environ.witx
phases/old/snapshot_0/docs.md
phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/docs.md
phases/snapshot/witx/wasi_snapshot_preview1.witx

This commit fixes wording and return args naming in `environ_sizes_get`
syscalls across all snapshots. It seems that the wording for `args_sizes_get`
was copied over to `environ_sizes_get` but without adjusting the wording
and naming.

Fix wording and return args in environ_sizes_get syscall

---

phases/ephemeral/witx/wasi_ephemeral_clock.witx
phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx

This is merely a stylistic nit which strives to maintain consistency
across all WASI syscalls in that `param`s *always* precede `result`s
in `*.witx` specs.

Reorder params/results in clock_res_get syscall

---

tools/witx/Cargo.toml
tools/witx/src/parser.rs

This updates the necessary glue to parse annotations, since the `wast`
crate now has more official support for annotations.

Update the wast crate in the witx tool

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

Add a simple documentation comment for the `$size` type.

Add a documentation comment for the `$size` type.

---

phases/old/snapshot_0/docs.md
phases/old/snapshot_0/witx/typenames.witx
phases/snapshot/docs.md
phases/snapshot/witx/typenames.witx

This commit backports fd as handle to past and current snapshots. I'm hoping this could prove useful in situations where currently in the implementor's code, any syscall that deals with `fd`s has to be marked as potentially "unsafe", whereas with `fd` as a handle this would be shifted to the fact that `fd` *is* a handle rather than an alias to an int type.
To put it more into context. Currently, in `wasmtime`, whenever we deal with a WASI fd type in a syscall, we tag the function as `unsafe` which makes perfect sense. The question here then is: could we assume it is safe if the fd was a handle rather than an alias to an int type?
Either way, even if this won't really help with this question, @pchickey and myself still think it's useful to have handles backported to all historic snapshots …

Backport fd as handle to past and current snapshots

---

meetings/2019/WASI-11-21.md
meetings/2019/WASI-12-05.md
meetings/2019/WASI-12-19.md
meetings/2020/WASI-01-16.md
meetings/2020/WASI-02-27.md
meetings/2020/WASI-03-12.md
meetings/README.md

This catches up on adding meeting notes to the repo, and adds an initial agenda for the upcoming meeting. We can add agenda items as needed!
Also, in general, when attending meetings, please help take notes! All help is appreciated :-).

Add an agenda for the 03-12 meeting, and add notes for prior meetings

---

tools/witx/tests/wasi.rs

The invocation for the docs generator changed with #243 .  Remembered this right after I merged.

fix error message when docs out of date

---

tools/witx/src/ast.rs

In the wiggle code generator, we require that the error types of a given Document implement certain traits. This method iterates over all of the unique types that are used as error types in a Document.
I'll release this as 0.8.5 once its merged.

witx: expose iterator of all error types

---

docs/Process.md
docs/Proposals.md
phases/README.md

Adapt the WebAssembly CG's phases process for WASI, and make an
initial mapping of current WASI proposals to phases within this
process. This is quite rough at this time, and not everything
fits in quite yet, and we can adjust things. This is a first
step, and we'll work for greater harmonization as we proceed.

Start moving WASI to a CG-style phases process.

---

design/application-abi.md

This adds a new reactor ABI, indicated by exporting the function
"_activate". For now, a reactor is just a module which doesn't have
a lifetime scoped by a "_start" or "main" function, though it may
evolve to include other semantics in the future.

Describe a primitive reactor ABI.

---

phases/ephemeral/docs.md
phases/old/snapshot_0/docs.md
phases/snapshot/docs.html
phases/snapshot/docs.md
tools/witx/src/docs/ast.rs

closes #266 
This adds documentation for all the sizes, alignments, and offset of data types, structs, and unions for `.witx` documents. :smile: :+1: 
cc @pchickey for the review :smile: 
*I was using a local md to html converter to view the doc, which is why it looks a little funny :smile: *

Added sizes and alignments to WASI docs

---

phases/old/snapshot_0/docs.md
phases/old/snapshot_0/witx/typenames.witx
phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/docs.md
phases/snapshot/witx/typenames.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx

This commit fixes links in `fd_readdir` description/docs which were
using an outdated (now invalid) ref syntax when referencing `dirent`
struct.
The changes apply to docs only and only to `wasi_unstable` and
`wasi_snapshot_preview1` snapshots. The `wasi_ephemeral` has properly
referenced links.

Fix links to dirent struct in fd_readdir description

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

As suggested by @sunfishcode in https://github.com/bytecodealliance/wasmtime/issues/273

Document why there is no path_filestat_set_size

---

phases/old/snapshot_0/docs.md
phases/old/snapshot_0/witx/typenames.witx
phases/snapshot/docs.md
phases/snapshot/witx/typenames.witx

This commit fixes an outdated ref syntax when referencing back to
`event` struct.

Fix link to event struct

---

phases/ephemeral/docs.md
phases/ephemeral/witx/typenames.witx

Just a minor (although ABI breaking) nit suggestion that stuck out to me when implementing `fd_readdir`.
Currently `$dirent` has the filetype in-between the name length and the name data so you end up scanning the length of entry's name, writing the type of the entry then going back to write out the name data.

Move $d_namlen to the end of $dirent

---

phases/ephemeral/docs.md
phases/ephemeral/witx/wasi_ephemeral_fd.witx

See the commit message of each commit for details.

Document atomicity of `write` and `pwrite`, and technical fix about POSIX

---

design/application-abi.md

This pulls out the parts of #281 which document existing practice.

Elaborate on the definitions of commands and reactors.

---

phases/README.md

The link now properly renders, and leads to... the README itself?
Should it even be kept (or maybe changed to lead elsewhere)?

Fix link in phases/README.md

---

tools/witx/Cargo.toml

the latest `wast` is `20.0.0`, and we can bump the crate version to `0.8.6`

witx crate: bump dep version, crate version

---

.github/workflows/main.yml

In accordance with this advisory it's recommended we move to a
different scheme of setting env vars and updating PATH:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

CI: use $GITHUB_PATH rather than add-path

---

design/application-abi.md

I couldn't find a modules.md anywhere else in this repo to link to, so just removed the broken reference.

Remove reference to non existent modules.md file

---

README.md
docs/Proposals.md

This also tweaks the proposals page and adds the proposals page to the main README (re-organizing it a bit in the process).

Add wasi-nn to proposals

---

docs/Proposals.md

See notes for [2020-10-22 subgroup meeting](https://docs.google.com/document/d/1uGgt-M6iHUzXTYk8Uuc5dohJ0EIwWft_Kz9aFuQi2zI).

Move wasi-nn to phase 2

---

README.md
docs/README.md

As discussed in https://github.com/WebAssembly/WASI/pull/329#discussion_r505020459, this change creates a landing page explaining roughly what you get in each of the documentation pages and moves the helpful links from the main README to this page.

Create documentation landing page

---

meetings/2020/WASI-11-19.md

This updates the agenda from 11-05 which didn't happen due to meeting
logistics, and adds another link for the case insensitivity discussion.

Add an agenda for the 11-19 meeting.

---

tools/witx/src/ast.rs
tools/witx/src/parser.rs
tools/witx/src/render.rs
tools/witx/src/representation.rs
tools/witx/src/validate.rs

the idea here was to enable handles to have a subtyping hierarchy,
but this isnt compatible with wasm extern refs and we never used it
anywhere, so its safe to delete all this code.
See also #357

witx: remove supertypes from the handle type

---

meetings/2021/WASI-01-14.md
meetings/2021/WASI-01-28.md
meetings/README.md

We probably shouldn't start any new projects right before the holidays and we don't have any urgent old business to close out, so I'm planning to cancel the meeting on Thursday.
In January, we'll be able to start on some interesting work, including defining testing guidelines for proposals and starting to switch over to interface types for handles. I added agendas including this work. 
I'll leave this issue open for a few hours in case anyone has an urgent agenda item for Thursday, but barring that, I'll go ahead and cancel.

Cancel 12-17 meeting and add agendas for 01-14 and 01-28.

---

phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx
tools/witx/Cargo.toml
tools/witx/src/render.rs

The noreturn annotation was invented solely for the sake of proc_exit,
but we never actually used it in the spec documents.
This annotation sets the `noreturn` bit in the `InterfaceFunc` struct.
Downstream tools are free to do with that bit what they will.

Add the `(@witx noreturn)` annotation to proc_exit

---

docs/DesignPrinciples.md
docs/Proposals.md
meetings/2019/WASI-05-02.md
meetings/2019/WASI-05-16.md
meetings/2019/WASI-05-30.md
meetings/2019/WASI-06-27.md
meetings/2019/WASI-07-18.md
meetings/2019/WASI-10-15.md
phases/README.md
phases/old/snapshot_0/witx/typenames.witx
snapshots/make-snapshot.sh

correct WASI branch name references from `master` to `main`

---

docs/Proposals.md

This updates the Proposals.md page, fixing a few broken links, and
updating the names of the proposals to match the actual proposal
repositories.

Update the Proposals.md links to match the proposals repositories.

---

phases/ephemeral/docs.md
phases/ephemeral/witx/wasi_ephemeral_args.witx
phases/ephemeral/witx/wasi_ephemeral_environ.witx
phases/old/snapshot_0/docs.md
phases/old/snapshot_0/witx/wasi_unstable.witx
phases/snapshot/docs.md
phases/snapshot/witx/wasi_snapshot_preview1.witx

Documents the answers I recieved in https://github.com/WebAssembly/WASI/issues/396 .  Hopefully I'm doing this right!

Document `=` and `\0` use in args/environ docs.

---

meetings/2021/WASI-03-11.md
meetings/2021/WASI-03-25.md

Github doesn't make it easy to read the HTML files checked into the repo from the online interface, so add links to the PDF documents.

Link to the pdf, which can be read without making a clone of the repo.

---

phases/ephemeral/witx/typenames.witx
phases/old/snapshot_0/witx/typenames.witx
phases/snapshot/witx/typenames.witx
tools/witx/src/ast.rs
tools/witx/src/parser.rs
tools/witx/src/toplevel.rs
tools/witx/src/validate.rs
tools/witx/tests/witxt.rs
tools/witx/tests/witxt/abi.witxt
tools/witx/tests/witxt/anonymous.witxt
tools/witx/tests/witxt/resources.witxt
tools/witx/tests/witxt/resources/multi.witx
tools/witx/tests/witxt/resources/other.witx

This commit reworks how handle types work at the representation level in
`*.witx` file to follow the expected design of resources in the
interface types specification. Previously handle types were simply
`(handle)`, which meant that there could only be one actual handle type
in the world (structurally at least). After this commit, however, there
can be multiple handle types.
First abstract types must be introduced as a `resource`, for example:
(resource $fd)
This declares that the module exports a type named `$fd` and it's
abstract in that the representation is not known. At the interface layer
you can't pass an `$fd` directly because it's representation is not
known. To do that, however, you can do:
(param $x (handle $fd))
The `handle` type now refers to a particular `resource` that it …

Enable more than one `handle` type in `*.witx`

---

meetings/2021/WASI-05-06.md

This will be the last set of meeting agendas/notes posted to this repo. After this, they will move to the [WebAssembly meetings repo](https://github.com/WebAssembly/meetings).

Add 05-06 meeting notes

---

tools/witx/src/io.rs
tools/witx/src/toplevel.rs

:bat: :sparkles: **Hello**!
This branch fixes a bug I have found in the `witx` crate, involving `use` statements.
:bug: **The Bug**
Paths in .._transitive_(?) `use` statements (_e.g. document A imports document B, which imports document C_) are evaluated relative to the original root document, rather than the import-_er_ document B.
This is better understood with an example (_see below_), or consulting the test case added here, `multi_use_with_layered_dirs`. Note that unlike the existing `multi_use` test, these documents do not all live within the same directory in the file system.
:scroll: **Example**
```
;; /root.witx
(use "subdir/child.witx")
```
```
;; /subdir/child.witx"
(use "sibling.witx")
(typename $b_float f64)
```
```
;; /subdir/sibling.witx
(typename $c_int u32)
```
Today, when …

Fix path canonicalization in witx `use` statements

---

tools/witx/src/lib.rs
tools/witx/src/phases.rs

Per this discussion from #434:
> It looks like the crate was last published at
> [7ec4b1a](https://github.com/WebAssembly/WASI/commit/7ec4b1a65621ed3dd98fb67ab3746b4f29b4a62b)
> ([diff from
> `main`](https://github.com/webassembly/WASI/compare/ef8c1a53feb2dfb763d4ea5c7d9e0a0126b45579...main)),
> and if we'd like to make an 0.9.1 release (ideally just a bugfix
> release), I think there's another breaking change we merged in the
> meantime, notably the deletion of `tools/witx/src/phases.rs`, which I
> think happened as #398. I think we may need to revert that as well
> before publishing 0.9.1?
-- [@alexcrichton](https://github.com/WebAssembly/WASI/pull/434#issuecomment-866050346)
This reintroduces 'witx::phases', so that we do not include any breaking
changes in what ought to be a pure bug …

reintroduce witx::phases (partial revert #398)

---

phases/snapshot/docs.md
phases/snapshot/witx/typenames.witx
phases/snapshot/witx/wasi_snapshot_preview1.witx

Today (2022-01-13) we discussed this PR in the WASI subgroup call. There was general agreement that updating snapshot1 with an `accept()` call was a valuable endeavor. I have updated the PR as I believe it is now ready for merge.
Although this proposal previously suggested the publication of a `snapshot2`, the consensus on the call was that implicitly updating `snapshot1` is the preferred route.
This proposal needs to be adopted and implemented in the `libc` implementation before transitioning to streams so that consumers can lock to an older version (per @sunfishcode).
WASI snapshot1 is very broadly implemented. It is also fairly usable for a number of cases. However, for networking its use is quite limited. This is particularly because there are a few omissions that create real blockers …

Add `sock_accept()` to snapshot1

---

legacy/application-abi.md

The core idea of legacy commands is that all function exports are
command entrypoints, and they expect to be called on a fresh instance
which lives only for the direction of the call.
This is a generalization of the existing `_start` convention, which
already has the expectation of a fresh instance  which lives only for
the direction of the call, and is one of the pieces need to enable
user-defined command entrypoints which don't take string arguments and
don't return an i32 status code.
To show how this works in practice, the following patches implement
this new behavior in wasm-ld and wasi-libc:
- https://reviews.llvm.org/D81689
- https://github.com/WebAssembly/wasi-libc/pull/203

Describe legacy commands.

---

Proposals.md
phases/ephemeral/witx/typenames.witx
phases/ephemeral/witx/wasi_ephemeral_clock.witx
phases/ephemeral/witx/wasi_ephemeral_environ.witx
phases/ephemeral/witx/wasi_ephemeral_path.witx
phases/ephemeral/witx/wasi_ephemeral_poll.witx
phases/ephemeral/witx/wasi_ephemeral_proc.witx
phases/ephemeral/witx/wasi_ephemeral_random.witx
phases/ephemeral/witx/wasi_ephemeral_sched.witx
phases/ephemeral/witx/wasi_ephemeral_sock.witx

Since the witx document is moved to `tools/witx-docs.md`, this PR fix all links to the new witx document.

Fix broken links to the witx documents

---

Proposals.md

It's now clear that wasi-handle-index is being subsumed by the component model definition of handles, so we no longer need a proposal repository for it.
wasi-classic-command will be replaced by an upcoming command proposal based on the new World concept in the component-model.

Remove the handle-index and classic-command proposals.

---

legacy/preview1/witx/wasi_snapshot_preview1.witx

As discussed in the the 02-09 meeting, explicitly document that Preview1's `fd_readdir` includes the `.` and `..`.
This resolves WebAssembly/wasi-testsuite#52.

Explicitly document that Preview1's `fd_readdir` includes `.` and `..`.

---

README.md

While the original goals of capability-based security and interposability remain, these goals have been factored out into the component model, so we now update WASI to refer to the component model rather than defining these concepts itself.

Update the design principles in the README.md

---

Contributing.md
README.md
docs/WitInWasi.md

Add a "Wit in WASI" document explaining how to use Wit in WASI proposals, including some conventions, and the recommended workarounds for component-model features that are not available yet.

Add a "Wit in WASI" document.

---

legacy/application-abi.md

Add documentation mentioning stdin, stdout, and stderr file descriptors, and also preopen file descriptors, and mention that preopen file descriptors can be closed.
Allowing preopen file descriptors to be closed is a change from how Wasmtime historically worked, but I think it's more clear now that it's ok to let preopens be closed. We'll change Wasmtime accordingly.
This addresses WebAssembly/wasi-testsuite#50.

Add documentation about starting file descriptors in Preview1.

---

Proposals.md

The link to wasi-digital-io now goes to correct repository.

Fix broken link wasi-digital-io

---

legacy/tools/witx-docs.md

Document how return types, in particular `expected` return types, work in witx.
Also update the witx-docs.md file to describe the current status of witx and the transition to wit.

Add documentation for return types and pointer types in witx.

---

LICENSE.md

This is a copyright and license description, which I have translated from HTML to Markdown, as found in https://www.w3.org/community/reports/reqs/ for use in draft reports.
I consulted with the Wasm CG chairs @dtig @dschuff @conrad-watt and we believe that this is an appropriate license to include in the WASI proposal repositories.

add LICENSE.md, following the W3C CLA Deed

---

Proposals.md

I feel [the proposal](https://github.com/WebAssembly/wasi-sockets) is coming along quite nicely. It's slated to be included in Preview2.
Before scheduling a vote, I thought I'd test the waters here first. 
Are there any things you'd like me to do, to make the proposal Phase 2-worthy?

Advance wasi-sockets to phase 2

---

Proposals.md

SingleStore is no longer pursuing wasi-data and @ricochet, it's champion, has decided not to pursue it further independently.

Remove WASI-Data as a proposal

---

legacy/tools/witx-docs.md

discussion: https://github.com/WebAssembly/WASI/issues/505

Document that an out-of-bounds pointer shall trap

---

Contributing.md

The [CG Phase Process document] has recently split out the entry requirements for each stage from the activities that happen within each stage, fixing an ambiguity about what happens before a stage and what happens within a stage. It also contains a number of generally useful updates.
This PR updates the WASI Phase Process using wording derived from the CG Phase Process, adapting it to meet WASI's needs. The resulting process is roughly the same as the existing process, however I've made it more specific in a few areas:
- Phase 2 requires a wit description.
- Phase 3 requires there be a plan for how the phase 4 accpetance criteria will be met.
[CG Phase Process document]: https://github.com/WebAssembly/meetings/blob/main/process/phases.md

Rebase the Phase Process description on the CG's current process

---

legacy/preview1/witx/wasi_snapshot_preview1.witx

`readlink` and `readlinkat` in POSIX specify that if the buffer is too small to contain the link content, the first `buf_len` bytes will be written. We already state the behaviour of this function is similar to `readlinkat` but explicitly clarifying this case removes any ambiguity.
I ran into this issue when [fixing the WASI tests for WAMR](https://github.com/WebAssembly/wasi-testsuite/pull/85/files#r1321869236). Alternatively, if we don't want to enforce this behaviour, I can modify the PR to state the behaviour is undefined when the buffer is too small (currently wasmtime returns an error in this case). Given the current docs mention `readlinkat`, I think it's reasonable to assume the behaviour is the same unless specified otherwise.
Please let me know if there any other concerns or …

Document behaviour of path_readlink when buf is too small

---

legacy/application-abi.md

I've fixed a typo in legacy/application-abi.md

Fix typo in legacy/application-abi.md

---

legacy/preview0/witx/typenames.witx
legacy/preview0/witx/wasi_unstable.witx
legacy/preview1/witx/typenames.witx
legacy/preview1/witx/wasi_snapshot_preview1.witx

The https://github.com/WebAssembly/WASI/tree/main/docs/witx.md links in the legacy witx files are broken from files being moved in #451 moved docs/witx.md, so I updated them to the (currently) working link https://github.com/WebAssembly/WASI/blob/main/legacy/tools/witx-docs.md

Fix WITX docs links in legacy files

---

Proposals.md

Emiel has passed championship of wasi-i2c to Friedrich Vendenberghe

wasi-i2c champion change

---

docs/WitInWasi.md

The component model now has support for resources, and WASI is now updated to use them, so we can remove the documentation section about working around the lack of resources.
Also, polling has moved from wasi-poll to wasi-io.

Remove the documentation about pseudo-handles.

---

preview2/README.md

Add some more documentation about what WASI Preview 3 is expected to be about: replacing wasi-io with future, stream, integrated async, and also incorporating lessons learned. And also mention how implementations may continue to support Preview 2 even after Preview 3 is launched.

Expand on the documentation describing Preview 3.

---

preview2/README.md

Document that WASI Preview 2 corresponds to “WASI 0.2” and version numbers `0.2.x` in the official Wit files and import identifiers. And document that “WASIp2” is also a name in common use.

Document that "WASI Preview 2" corresponds to “WASI 0.2” and “WASIp2”.

---

Proposals.md

Hi! This adds a phase 0 proposal for a WASI Observe interface. There's an open discussion issue [here](https://github.com/WebAssembly/wasi-observe/issues/10) and a call for participants issue [here](https://github.com/dylibso/wasi-observe/issues/1). If desired, I can transfer the repo over to WebAssembly on request!
(Thanks for taking a look at this!)

Add wasi-observe proposal at Phase 0

---

Proposals.md

To bring the co-champions in-line with https://github.com/WebAssembly/wasi-i2c

Update I2C co-champions

---

Proposals.md

This adds a stage 0 proposal to extend `wasi:clocks` with basic timezone support. @sunfishcode is the current champion for `wasi:clocks` and has volunteered to also be the champion for this extension. The related PR for this on the `wasi:clocks` side are: https://github.com/WebAssembly/wasi-clocks/pull/61 and https://github.com/cdmurph32/wasi-clocks/pull/1.
This proposal is a little different from the other proposals so far: rather than introducing something new, this *extends* an existing stage 3 proposal. The expectation is that we will want to advance this independently from `wasi:clocks` through the phase process, and will be voted on by the SG. Tracking this independently gives us the flexibility we need for that.
Additionally, this also gives the `timezone` proposal a concrete name. …

Add `Clocks: Timezone` as a stage 0 proposal

---

Proposals.md

As per the 2024-06-13 WASI SG meeting: the timezone extension to `wasi:clocks` already meets the phase 2 criteria by virtue of being part of an existing phase 3 proposal. It should have been introduced at phase 2, not phase 0. This allows it to be introduced as `@unstable` and be implemented by runtimes, but still needs a vote before it can be stabilized behind an `@since` gate.
I'll file a follow-up PR to clarify the process changes to existing proposals should go through, so we can follow this same process for other changes too.

Re-file the `wasi:clocks` timezone extension as phase 2

---

Proposals.md

Both specs have already been accepted to phase 2, it was just not yet reflected in the WASI spec proposals page. Thanks!

move `wasi:keyvalue` and `wasi:runtime-config` to phase 2

---

Contributing.md

As promised in [last week's WASI meeting](https://github.com/WebAssembly/meetings/blob/main/wasi/2024/WASI-06-13.md#progressing-proposal-amendments-through-the-phase-process), this describes the process people should follow to file API changes to existing phase 3 proposals. As discussed in the meeting this should strike a good balance between champion agency, and checks by the subgroup. I hope that comes through in this process; for additional context please [see my presentation slides](https://github.com/WebAssembly/meetings/blob/main/wasi/2024/presentations/2024-06-13-yosh-wuyts-progressing-proposal-changes-through-the-phase-process.pdf). Thanks!

Add section on filing changes to existing phase 3 proposals

---

Proposals.md

Begins tracking https://github.com/WebAssembly/wasi-cli/pull/44 as unstable. Thanks!

Track cli: exit with code

---

Proposals.md

Caleb has been doing an outstanding job of pushing wasi-observe forward. I think he'll do a great job as champion of this effort.

wasi-observe: add Caleb Schoepp as champion, remove myself

---

Proposals.md

WASI follows its own phase process, which is based on the Wasm CG's phase process, rather than using the Wasm CG's phase process directly.

Fix the link to WASI's phase process.

---

Proposals.md

We noticed that `wasi-i2c`'s phase wasn't updated after moving to phase 2 as [discussed during the WASI SG meeting of May 16 2024](https://github.com/WebAssembly/meetings/blob/main/wasi/2024/WASI-05-16.md). This small PR fixes that.

Move `wasi-i2c` to phase 2

---

docs/Capabilities.md

We use the word "capabilies" a lot in WASI; add a document defining what we mean, and what the diffence is between link-time and runtime capabilities.

Add a document defining what we mean by "capabilities".

---

docs/Capabilities.md

```diff
- The Wasm language has no syscall instructions or builtin I/O facilities.
+ The Wasm language has no syscall instructions or built-in I/O facilities.
- Link-time capabilities may also be called *instantiation-time* capabilties,
+ Link-time capabilities may also be called *instantiation-time* capabilities,
```

Capabilities.md: Fix typo

---

Proposals.md
wasip2/http/handler.wit
wasip2/sockets/tcp.wit
wasip2/sockets/udp.wit

https://pypi.org/project/codespell
% `codespell --ignore-words-list=wit --skip="./legacy/*" --write-changes`
This assumes that we should not modify the files in the `legacy` directory.

Fix typos discovered by codespell

---

Proposals.md

wasi-messaging was approved to move to Phase 2 during the WASI Subgroup Video Meeting of November 14th. This PR updates the status of wasi-messaging in the Proposals.md document.

[proposal update] Moving wasi-messaging to Phase 2

---

Proposals.md

This is a reversal of https://github.com/WebAssembly/WASI/pull/632 which was filed in response to https://github.com/WebAssembly/WASI/issues/631. The issue asserts that both the `@unstable` "timezones" (clocks) and "exit with status" (cli) features are at phase 3. To reach phase 3 these proposals would need to have gone through a WASI SG vote, after which they can be changed from `@unstable` to be marked `@since` instead. This vote was never held, and so the proposals cannot be at phase 3.
Here are the relevant sections from [the phase process documentation](https://github.com/WebAssembly/WASI/blob/main/Contributing.md#filing-changes-to-existing-phase-3-proposals):
> 3. Once the champion is ready to merge the proposal, they will submit a PR to the WASI repository (this repository) to file …

Revert accidental stabilization in the proposal tracker of unstable sub-proposals

---

wasip2/cli/command.wit
wasip2/cli/imports.wit
wasip2/cli/stdio.wit
wasip2/clocks/monotonic-clock.wit
wasip2/clocks/timezone.wit
wasip2/clocks/wall-clock.wit
wasip2/clocks/world.wit
wasip2/filesystem/preopens.wit
wasip2/filesystem/types.wit
wasip2/filesystem/world.wit
wasip2/http/proxy.wit
wasip2/http/types.wit
wasip2/io/error.wit
wasip2/io/poll.wit
wasip2/io/streams.wit
wasip2/io/world.wit
wasip2/random/insecure-seed.wit
wasip2/random/insecure.wit
wasip2/random/random.wit
wasip2/random/world.wit
wasip2/sockets/ip-name-lookup.wit
wasip2/sockets/network.wit
wasip2/sockets/tcp.wit
wasip2/sockets/udp.wit
wasip2/sockets/world.wit

Pulls in the latest WASI WIT definitions (v0.2.5). This was mechanically generated by running the following command:
```bash
echo 'io = "https://github.com/WebAssembly/wasi-io/archive/v0.2.5.tar.gz"
random = "https://github.com/WebAssembly/wasi-random/archive/v0.2.5.tar.gz"
clocks = "https://github.com/WebAssembly/wasi-clocks/archive/v0.2.5.tar.gz"
filesystem = "https://github.com/WebAssembly/wasi-filesystem/archive/v0.2.5.tar.gz"
sockets = "https://github.com/WebAssembly/wasi-sockets/archive/v0.2.5.tar.gz"
cli = "https://github.com/WebAssembly/wasi-cli/archive/v0.2.5.tar.gz"
http = "https://github.com/WebAssembly/wasi-http/archive/v0.2.5.tar.gz"' > deps.toml
wit-deps -d wasip2 -m deps.toml -l deps.lock
rm deps.toml
rm deps.lock
```
Thanks!

Update to v0.2.5

---

legacy/preview1/docs.md

Since sync flag functionality is entirely dependent on the host platform, add a caveat for each sync flag, warning that functions may return ENOTSUP if an unsupported sync flag is set.

Add caveat about support for sync flags
