WebAssembly/WASI

- README.md
- meetings/2019/WASI-05-02.md
- meetings/README.md
See https://github.com/WebAssembly/WASI/issues/11 for background discussions.
> Post the schedule for the first meeting.

- meetings/README.md
Also remove used of embedded html in the md file.  It seems somewhat
unnecessary.
> Add May 16 meeting to index

- meetings/2019/WASI-08-30.md
- meetings/README.md
Note that as discussed in the previous meeting, we're changing the time
for this meeting to accomodate people in different time zones.
> Add a preliminary agenda for the WASI-08-30 meeting.

- phases/README.md
This PR is proposed to fix a format error after #88 being merged.
> Fix a format error in phases module

- phases/ephemeral/witx/typenames.witx
Add a comment mentioning the special value of `dircookie_t`.
> Document the special meaning of `dircookie_t` value 0.

- meetings/2019/WASI-10-24.md
- meetings/2019/WASI-11-07.md
- meetings/README.md
Note the time change, due to daylight savings time changes in some
locales. We can of course discuss changing back for the following
meeting if people prefer that.
Also post the 10-24 meeting notes.
> Post an initial agenda for the 11-07 meeting.

- meetings/2019/WASI-11-07.md
- meetings/2019/WASI-11-21.md
- meetings/README.md
Also, post the notes for the 11-07 meeting.
> Announce the 11-21 meeting.

- .github/workflows/main.yml
To avoid effects of changes on their master branch.
See https://github.com/CraneStation/wasi-libc/pull/145
> github actions: pin version of the checkout action

- phases/ephemeral/witx/typenames.witx
- tools/witx/src/ast.rs
- tools/witx/src/coretypes.rs
- tools/witx/src/docs.rs
- tools/witx/src/layout.rs
- tools/witx/src/lib.rs
- tools/witx/src/parser.rs
- tools/witx/src/render.rs
- tools/witx/src/validate.rs
This will allow us to auto-generate the `DIRCOOKIE_START` constant.
> Add an int typedef kind, which is like enum but not expected to be exhaustive

- phases/ephemeral/docs.md
- phases/ephemeral/witx/typenames.witx
It's not clear which is correct, but `pemissions_set` seems to be used more frequently.
> change set_permissions to permissions_set

- tools/witx/Cargo.toml
- tools/witx/src/lib.rs
Forgot to add this to the crates exports.
> witx: export UnionLayout type

- phases/ephemeral/docs.md
- phases/ephemeral/witx/typenames.witx
- phases/ephemeral/witx/wasi_ephemeral_clock.witx
- phases/ephemeral/witx/wasi_ephemeral_fd.witx
- phases/ephemeral/witx/wasi_ephemeral_path.witx
- phases/old/snapshot_0/docs.md
- phases/old/snapshot_0/witx/typenames.witx
- phases/old/snapshot_0/witx/wasi_unstable.witx
- phases/snapshot/docs.md
- phases/snapshot/witx/typenames.witx
This commit fixes dead links (most likely not all of them, but at least
a large number) across all snapshots.
> Fix dead links across all snapshots

- tools/witx/Cargo.toml
> witx: Update to current wast 8.0.0

- tools/witx/Cargo.toml
only change should be fewer deps than previously
> bump witx to 0.8.4

- tools/witx/Cargo.toml
> Update some witx Rust dependencies

- meetings/2020/WASI-03-12.md
- meetings/2020/WASI-03-26.md
- meetings/README.md
And add the notes for the 03-12 meeting.
> Add an agenda for the 03-26 meeting.

- meetings/2020/WASI-05-07.md
- New proposal process updates.
- witx planning
- Update on the module-types linking proposal.
> Add some agenda topics.

- docs/DesignPrinciples.md
I guess this is the best section to link so far.
> Fix: Broken link in DesignPrinciples.md #269

- meetings/2020/WASI-04-09.md
- meetings/2020/WASI-05-07.md
- meetings/2020/WASI-05-21.md
- meetings/2020/WASI-06-04.md
- meetings/README.md
Also add the meeting notes for the last few meetings.
> Add an agenda for the 06-04 meeting.

- Charter.md
This is a very fascinating project, thanks for your work and dedication :1st_place_medal:
> Improve spelling of README.md

- tools/witx/Cargo.toml
wast dep from `20.0.0` => `22.0.0`
witx version from `0.8.6` => `0.8.7`
> latest wast in witx

- meetings/2020/WASI-10-08.md
I'm working on catching up here, please feel free to bring up additional topics!
> Add several meeting agenda items.

- meetings/2020/WASI-10-22.md
Add proposal to cover WASI Logo in next WASI meeting
> WASI Logo in next WASI meeting

- meetings/2020/WASI-10-22.md
There are several discussions going about character encodings and
strings across different forums. This presentation will summarize
the current conversations and discuss the high-level pros and cons
of various options being discussed.
> Add an agenda item for a presentation on character encodings.

- meetings/2021/WASI-04-22.md
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
> Add Proxy-Wasm update to 4/22 agenda.

- tools/witx/Cargo.toml
witx: Update `wast` dependency
> witx: Update wast dependency

- tools/witx/Cargo.toml
- tools/witx/cli/Cargo.toml
I'll publish this to crates.io after merging, and I also just
double-checked to ensure we don't have any other accidental API breakage
leaking in.
> Bump to 0.9.1

- docs/Proposals.md
> Add link to networking proposal.

- Proposals.md
> Progress wasi-sockets to phase 1

- phases/README.md
The old Process.md content has been moved to a new Contributing.md page. Update a link to point to the new page.
> Update the process link

- Proposals.md
> Add Radu Matei as a Champion of wasi-url

- Proposals.md
Added Marcin and Andrew to wasi-threads proposal
> Updated wasi-threds proposal champions

- phases/snapshot/docs.html
- phases/snapshot/docs.md
- phases/snapshot/witx/wasi_snapshot_preview1.witx
fix an error here. `fsync`->`fcntl`
> Fix error in snapshot/doc.md

- phases/snapshot/docs.md
> Fix POSIX equivalent for fd_fdstat_get

- Proposals.md
wasi-cli was accepted as phase 1 in the 2023-02-23 WASI SG meeting.
> Add wasi-cli as a phase-1 proposal.

- Proposals.md
> remove wasi-grpc from Proposals.md

- Proposals.md
https://github.com/WebAssembly/wasi-http/pull/51
> add Luke Wagner to wasi-http champions

- Proposals.md
as voted in WASI subgroup meeting on 09/21/2023
> wasi-http is now a phase 2 proposal

- Proposals.md
as passed with consensus vote in 10/5/2023 meeting https://github.com/WebAssembly/meetings/pull/1400
> move wasi-cli to phase 2

- Proposals.md
wasi io, clocks, random, filesystem, sockets, cli and http all advanced to phase 3, per votes in 11/30/2023 WASI meeting https://github.com/WebAssembly/meetings/pull/1443
> Advance proposals to phase 3

- Proposals.md
> Remove duplicated proposal

- preview2/README.md
> preview2/README: add missing link to test suite

- Proposals.md
> Move wasi-fgx to phase 2

- Proposals.md
> fix: update Proposals.md to reflect current state of proposals

- README.md
WASIp2 is now stable; update the README.md to mention this.
> Update README.md; WASIp2 is now stable.

- Proposals.md
Add wasi-tls as a phase 1 proposal with champions: @dicej, @badeend, and @jsturtevant.
> wasi-tls phase 1

- Proposals.md
Transfer championship to @merlijn-sebrechts for digital-io and spi per https://github.com/WebAssembly/wasi-digital-io/issues/1 and https://github.com/WebAssembly/wasi-spi/issues/2
> docs: transfer championship to merlijn

- .github/workflows/release.yaml
- scripts/wasi-deps.sh
Signed-off-by: Bailey Hayes <behayes2@gmail.com>
> feature: add release workflow
